In [1]:
import pandas as pd

hexsha_df = pd.read_csv('../../../../sample_data/data/camel_on_spiral/hexsha_filename_camel.txt', header=None, names=["id","commit_hash", "before_filename", "after_filename","change_type"])
label_df = pd.read_csv('../label/label_camel.csv')
vec_df = pd.read_csv('../resource/vec_camel_3.txt',header=None)

FileNotFoundError: [Errno 2] No such file or directory: '../../../../sample_data/data/camel_on_spiral/hexsha_filename_camel.txt'

In [ ]:
hexsha_df.head(5)

,id,commit_hash,before_filename,after_filename,change_type
0,1,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
1,2,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
2,3,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
3,4,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
4,5,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A

In [ ]:
label_df.head(5)

                                commit_hash  contains_bug
0  179b7ece6358193accd5759d5e307574b395a37d         False
1  e2d6c518df53fa0d06a7d308acff377993e80278         False
2  72bc6b0783cca7197f98911c2e88506789e0b960         False
3  630f1b90c8b007b62b514f579a2b3fca74fbc5d2         False
4  574012e334254dd94673745e44247a6e42361760         False

In [ ]:
vec_df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,1993,1994,1995,1996,1997,1998,1999,2000,idx,idx2
0,1-1,95,13,1,20,1,12,4,11,327,...,0,0,0,0,0,0,0,0,1,1
1,2-1,95,13,1,20,1,12,4,11,327,...,0,0,0,0,0,0,0,0,2,1
2,3-1,95,13,1,20,1,12,4,8,52,...,0,0,0,0,0,0,0,0,3,1
3,4-1,95,13,1,20,1,12,4,11,327,...,0,0,0,0,0,0,0,0,4,1
4,5-1,95,13,1,20,1,12,4,11,21,...,0,0,0,0,0,0,0,0,5,1

In [ ]:
vec_df[['id', 'id2']] = vec_df[0].str.split('-', expand=True)
vec_df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,1995,1996,1997,1998,1999,2000,idx,idx2,id,id2
0,1-1,95,13,1,20,1,12,4,11,327,...,0,0,0,0,0,0,1,1,1,1
1,2-1,95,13,1,20,1,12,4,11,327,...,0,0,0,0,0,0,2,1,2,1
2,3-1,95,13,1,20,1,12,4,8,52,...,0,0,0,0,0,0,3,1,3,1
3,4-1,95,13,1,20,1,12,4,11,327,...,0,0,0,0,0,0,4,1,4,1
4,5-1,95,13,1,20,1,12,4,11,21,...,0,0,0,0,0,0,5,1,5,1

In [ ]:
desired_columns = ['idx', 'idx2'] + list(vec_df.columns[vec_df.columns.isin(['idx', 'idx2', 0]) == False])
vec_df2 = vec_df[desired_columns]

In [ ]:
vec_df2

,idx,idx2,1,2,3,4,5,6,7,8,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000
0,1,1,95,13,1,20,1,12,4,11,...,0,0,0,0,0,0,0,0,0,0
1,2,1,95,13,1,20,1,12,4,11,...,0,0,0,0,0,0,0,0,0,0
2,3,1,95,13,1,20,1,12,4,8,...,0,0,0,0,0,0,0,0,0,0
3,4,1,95,13,1,20,1,12,4,11,...,0,0,0,0,0,0,0,0,0,0
4,5,1,95,13,1,20,1,12,4,11,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469851,215351,3,1,21,98,85,168,19,4,8,...,0,0,0,0,0,0,0,0,0,0
469852,215352,1,1,17,1,51,58,497,1,12,...,0,0,0,0,0,0,0,0,0,0
469853,215352,2,1,51,58,1,1382,1,155,1,...,0,0,0,0,0,0,0,0,0,0
469854,215353,1,1,17,1,51,58,497,1,12,...,0,0,0,0,0,0,0,0,0,0
469855,215353,2,1,51,58,1,1382,1,155,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
vec_df[1]

0         95
1         95
2         95
3         95
4         95
          ..
469851     1
469852     1
469853     1
469854     1
469855     1
Name: 1, Length: 469856, dtype: int64

In [ ]:
df = pd.merge(hexsha_df, label_df, on='commit_hash', how='left')

In [ ]:
df.head(5)

,id,commit_hash,before_filename,after_filename,change_type,contains_bug
0,1,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
1,2,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
2,3,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
3,4,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
4,5,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True

In [ ]:
df['contains_bug'].value_counts

NameError: name 'df' is not defined

In [2]:
import pandas as pd
label_df = pd.read_csv('../label/label_camel.csv')

In [3]:
label_df['contains_bug'].value_counts() / label_df.shape[0]

contains_bug
False    0.759661
True     0.240339
Name: count, dtype: float64

In [4]:
camel_df = pd.read_csv('../label/camel_info.csv', index_col=0, low_memory=False)
camel_df

,id,commit_hash,before_filename,after_filename,change_type,contains_bug
0,1,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
1,2,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
2,3,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
3,4,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
4,5,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A,True
...,...,...,...,...,...,...
215348,215349,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M,False
215349,215350,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M,False
215350,215351,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M,False
215351,215352,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M,False
215352,215353,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M,False

In [5]:
camel_10_df = pd.read_csv('../label/camel_10.csv', index_col=0)
camel_10_df

,id,id2,snippet_length,commit_hash,before_filename,after_filename,change_type
0,1,1,37,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
1,2,1,28,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
2,3,1,88,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
3,4,1,31,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
4,5,1,114,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
...,...,...,...,...,...,...,...
332394,215350,1,40,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
332395,215351,1,40,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
332396,215351,2,50,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
332397,215352,1,47,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
332398,215353,1,46,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M

In [6]:
merge_df = pd.merge(camel_10_df[['id','id2','commit_hash', 'change_type']], camel_df[['id','contains_bug']], on='id', how='left')
merge_df.head(36)

    id  id2                               commit_hash change_type contains_bug
0    1    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
1    2    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
2    3    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
3    4    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
4    5    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
5    6    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
6    7    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
7    8    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
8    9    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
9   10    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
10  11    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
11  12    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
12  13    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
13  14    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
14  15    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
15  16    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
16  17    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
17  18    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
18  19    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
19  20    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
20  21    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
21  22    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
22  23    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
23  24    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
24  25    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
25  26    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
26  27    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
27  28    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
28  29    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
29  30    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
30  31    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
31  32    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
32  33    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
33  34    1  77b260b65ba821b3443d922320cc3d9b708c8d83           A         True
34  69    1  a4701ac4bf5b50810914796e284b0e3f78a240bc           M         True
35  70    1  a4701ac4bf5b50810914796e284b0e3f78a240bc           M         True

In [7]:
except_a_df = merge_df[merge_df['change_type'] != 'A']
except_a_df

,id,id2,commit_hash,change_type,contains_bug
34,69,1,a4701ac4bf5b50810914796e284b0e3f78a240bc,M,True
35,70,1,a4701ac4bf5b50810914796e284b0e3f78a240bc,M,True
36,70,2,a4701ac4bf5b50810914796e284b0e3f78a240bc,M,True
37,70,3,a4701ac4bf5b50810914796e284b0e3f78a240bc,M,True
38,71,1,a4701ac4bf5b50810914796e284b0e3f78a240bc,M,True
...,...,...,...,...,...
332394,215350,1,e2d6c518df53fa0d06a7d308acff377993e80278,M,False
332395,215351,1,e2d6c518df53fa0d06a7d308acff377993e80278,M,False
332396,215351,2,e2d6c518df53fa0d06a7d308acff377993e80278,M,False
332397,215352,1,e2d6c518df53fa0d06a7d308acff377993e80278,M,False
332398,215353,1,e2d6c518df53fa0d06a7d308acff377993e80278,M,False

In [11]:
except_a_df['contains_bug'].value_counts() / except_a_df.shape[0]

contains_bug
True     0.586829
False    0.410598
Name: count, dtype: float64

In [8]:
merge_df['contains_bug'].value_counts() / merge_df.shape[0]

contains_bug
True     0.593702
False    0.403900
Name: count, dtype: float64

In [8]:
integrate_df = merge_df[['id','commit_hash','contains_bug']].groupby(['id','contains_bug'], as_index=False).count()
integrate_df

            id contains_bug  commit_hash
0            1         True            1
1            2         True            1
2            3         True            1
3            4         True            1
4            5         True            1
...        ...          ...          ...
158306  215349        False            2
158307  215350        False            1
158308  215351        False            2
158309  215352        False            1
158310  215353        False            1

[158311 rows x 3 columns]

In [9]:
integrate_df['contains_bug'].value_counts() / integrate_df.shape[0]

contains_bug
True     0.572708
False    0.427292
Name: count, dtype: float64

In [ ]:
camel_all = pd.read_csv('../resource/hexsha_filename_camel.txt',
                        header=None,
                        names=['id','commit_hash', 'before_filename', 'after_filename', 'change_type'])
camel_all

,id,commit_hash,before_filename,after_filename,change_type
0,1,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
1,2,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
2,3,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
3,4,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
4,5,77b260b65ba821b3443d922320cc3d9b708c8d83,camel/camel-core/src/main/java/org/apache/came...,camel/camel-core/src/main/java/org/apache/came...,A
...,...,...,...,...,...
215348,215349,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
215349,215350,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
215350,215351,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
215351,215352,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M
215352,215353,e2d6c518df53fa0d06a7d308acff377993e80278,components/camel-jsonpath/src/test/java/org/ap...,components/camel-jsonpath/src/test/java/org/ap...,M

In [ ]:
merge_all_df = pd.merge(camel_all[['id', 'commit_hash']], camel_df[['id','contains_bug']], on='id', how='left')
merge_all_df

            id                               commit_hash contains_bug
0            1  77b260b65ba821b3443d922320cc3d9b708c8d83         True
1            2  77b260b65ba821b3443d922320cc3d9b708c8d83         True
2            3  77b260b65ba821b3443d922320cc3d9b708c8d83         True
3            4  77b260b65ba821b3443d922320cc3d9b708c8d83         True
4            5  77b260b65ba821b3443d922320cc3d9b708c8d83         True
...        ...                                       ...          ...
215348  215349  e2d6c518df53fa0d06a7d308acff377993e80278        False
215349  215350  e2d6c518df53fa0d06a7d308acff377993e80278        False
215350  215351  e2d6c518df53fa0d06a7d308acff377993e80278        False
215351  215352  e2d6c518df53fa0d06a7d308acff377993e80278        False
215352  215353  e2d6c518df53fa0d06a7d308acff377993e80278        False

[215353 rows x 3 columns]

In [ ]:
merge_all_df['contains_bug'].value_counts() / merge_all_df.shape[0]

contains_bug
True     0.590797
False    0.406690
Name: count, dtype: float64